name: Release XCFramework 2

on:
  push:
    tags:
      - '*'  # Trigger the workflow when a tag like "v1.0.0" is pushed

permissions:
  contents: write  # Required to create releases and upload assets
  id-token: write   # Needed for upload

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0'

    - name: Create zip with xcframework
      run: |
        # Make sure the script is executable (just in case)
        chmod +x Framework/MyXC/build_xcframework.sh

        # Run the script to create the XCFramework
        ./Framework/MyXC/build_xcframework.sh

    - name: Compute Checksum
      id: checksum
      run: |
        # Compute checksum for the zipped xcframework
         swift package compute-checksum ./Framework/MyXC/MyXC.xcframework.zip
      shell: bash

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./Framework/MyXC/MyXC.xcframework.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     tag: ${{ github.ref_name }}
    #     name: Release ${{ github.ref_name }}
    #     body: |
    #       ### What's Changed
    #       - Add a description of changes here.
    #     draft: false
    #     prerelease: false
    #     artifacts: |
    #       ./Framework/MyXC/MyXC.xcframework.zip
